CREATE TABLE MANUFACTURERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- Table to store item types
CREATE TABLE ITEM_TYPES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- Table to store items
CREATE TABLE ITEMS (
    ID SERIAL PRIMARY KEY,
    MODEL VARCHAR(255) NOT NULL,
    TYPE_ID INT REFERENCES ITEM_TYPES(ID),
    DESCRIPTION VARCHAR(255),
    CONSTRAINT FK_ITEM_TYPE FOREIGN KEY (TYPE_ID) REFERENCES ITEM_TYPES(ID)
);

-- Table to store bikes
CREATE TABLE BIKES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL(10, 2) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'EUR' NOT NULL,
    MANUFACTURER_ID INT REFERENCES MANUFACTURERS(ID),
    CONSTRAINT FK_MANUFACTURER FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURERS(ID)
);

-- Table to represent the many-to-many relationship between bikes and items
CREATE TABLE REL_BIKES_ITEMS (
    BIKE_ID INT REFERENCES BIKES(ID),
    ITEM_ID INT REFERENCES ITEMS(ID),
    PRIMARY KEY (BIKE_ID, ITEM_ID),
    CONSTRAINT FK_BIKE FOREIGN KEY (BIKE_ID) REFERENCES BIKES(ID),
    CONSTRAINT FK_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID)
);

-- Search by name
CREATE INDEX idx_bike_name ON BIKES (NAME);

-- Search by manufacturer
CREATE INDEX idx_manufacturer_name ON MANUFACTURERS (NAME);

-- Search by item type
CREATE INDEX idx_item_type_name ON ITEM_TYPES (NAME);
