version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bike_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  bikes-api:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    restart: on-failure
    ports:
      - 8080:8080
    environment:
#      spring.cache.type: redis # cache disabled by error when connecting to redis "Unable to connect to Redis"
      spring.cache.type: none
      spring.cache.host: redis
      spring.cache.port: 6379
      spring.datasource.url: jdbc:postgresql://postgres:5432/bike_db
      spring.datasource.username: admin
      spring.datasource.password: pass
      spring.flyway.enabled: true
      spring.flyway.locations: classpath:migrations
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

networks:
  backend:
    driver: bridge
