version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bike_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
